---
title: "Directive 4"
subtitle: "Department of Biostatistics @ University of Washington"
author:
- Alejandro Hernandez
date: "Winter Quarter 2025"
output: pdf_document
---

```{r setup, include=F}
# Clear environment
rm(list=ls())

# Setup options
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, results='hide')
options(knitr.kable.NA = '-', digits = 2)
labs = knitr::all_labels()
labs = labs[!labs %in% c("setup", "allcode")]
```

```{r load}
# Load relevant packages
library(survival)  # survival models
library(dplyr)     # data manipulation
library(broom)     # combine and reshape model output
library(ggplot2)   # data visualization

theme_set(theme_bw())

# Load data
bmt <- read.csv("../data/bmt.csv")
dim(bmt) # 137 rows, 22 columns
names(bmt)

# Handle missing data (there is none)
anyNA(bmt)

```

```{r}

tbmt <- survival::tmerge(
  data1 = bmt, data2 = bmt, id = id,
  # Death
  death = event(ts, deltas),
  # Relapse
  relapse = event(tdfs, deltar),  
  # Death or relapse
  death.relapse = event(tdfs, deltadfs),  
  # Occurrence of aGVHD
  post.agvhd = tdc(ta),
  # Occurrence of platelet recovery
  post.recovery = tdc(tp)
  )

coxfit <- coxph(Surv(tstart, tstop, death.relapse) ~ post.agvhd + cluster(id), data = tbmt)
c(coef(coxfit), CI=confint(coxfit))

```

```{r}
tbmt <- survival::tmerge(
  data1 = bmt, data2 = bmt, id = id,
  # Death
  death = event(ts, deltas),
  # Relapse
  relapse = event(tdfs, deltar),
  # Death or relapse
  death.relapse = event(tdfs, deltadfs),  
  # Occurrence of aGVHD
  post.agvhd = tdc(ta),
  # Occurrence of platelet recovery
  post.recovery = tdc(tp)
  )

## Investigating acute graft-versus-host disease
# HR of disease-free survival associated with the occurrence of aGVHD 
coxfit <- coxph(Surv(tstart, tstop, death.relapse) ~ post.agvhd + cluster(id), data = tbmt)
summary(coxfit)
tidy(coxfit, conf.int = TRUE, conf.level = 0.95, exponentiate=TRUE)
exp(c(coef(coxfit), CI=confint(coxfit)))

# HR of relapse-free survival associated with the occurrence of aGVHD 
coxfit <- coxph(Surv(tstart, tstop, relapse) ~ post.agvhd + cluster(id), data = tbmt)
exp(c(coef(coxfit), CI=confint(coxfit)))

```



**End of report. Code appendix begins on the next page.**

\pagebreak

## Code Appendix

```{r allcode, ref.label = knitr::all_labels(), echo=TRUE, eval=FALSE}
```

**End of document.**