---
title: "Directive 3"
subtitle: "Department of Biostatistics @ University of Washington"
author:
- Alejandro Hernandez
date: "Winter Quarter 2025"
output: pdf_document
---

```{r setup, include=F}
# Clear environment
rm(list=ls())

# Setup options
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, results='hide')
options(knitr.kable.NA = '-', digits = 2)
labs = knitr::all_labels()
labs = labs[!labs %in% c("setup", "allcode")]
```

```{r load}
# Load relevant packages
library(survival)  # survival model
library(dplyr)     # data manipulation
# library(muhaz)     # hazard function
# library(msm)       # delta method
# library(knitr)     # pretty tables
# library(ggplot2)   # data visualization

# Load data
bmt <- read.csv("../data/bmt.csv")
dim(bmt) # 137 rows, 22 columns
names(bmt)

# Handle missing data (there is none)
anyNA(bmt)

```
3. Are any of the measured baseline variables associated with differences in disease-free survival?

```{r}
dfs_surv <- with(bmt, survival::Surv(tdfs, deltadfs))
sort(dfs_surv)

# disease group
coxph(dfs_surv ~ disgroup, bmt) # p=0.1
# fab
coxph(dfs_surv ~ fab, bmt) # p=0.005 < 5%
# mtx
coxph(dfs_surv ~ mtx, bmt) # p=0.1

# hospital
coxph(dfs_surv ~ hospital, bmt) # p=0.06 < 5%


## Patient
# age
coxph(dfs_surv ~ age, bmt) # p=0.3
# sex
coxph(dfs_surv ~ male, bmt) # p=0.3
# cmv
coxph(dfs_surv ~ cmv, bmt) # p=0.5

## Donor
# age
coxph(dfs_surv ~ donorage, bmt) # p=0.3
# sex
coxph(dfs_surv ~ donormale, bmt) # p=1
# cmv
coxph(dfs_surv ~ donorcmv, bmt) # p=0.8


```


**End of report. Code appendix begins on the next page.**

\pagebreak

## Code Appendix

```{r allcode, ref.label = knitr::all_labels(), echo=TRUE, eval=FALSE}
```

**End of document.**